### ISSUE TITLE
My project submission link.

### ISSUE THREAD

**Issue by kaksv** [horuslabsio/tokenbound-hackathon-submissions#3]
[**Here is my submission.** ](https://github.com/kaksv/tokenbound-hackathon-submissions) . https://github.com/kaksv/tokenbound-hackathon-submissions
This is because I have had issues submiting a pull request with this error: **There isn’t anything to compare.
horuslabsio:main and kaksv:main are entirely different commit histories**

**Comment by Darlington02** [comment]
Hey try deleting existing fork, re-forking and opening a PR again

**Comment by kaksv** [comment]
I have tried and I dont know where I am getting it wrong.

**Comment by kaksv** [comment]
Does my PR Show?

**Comment by kaksv** [comment]
Thank you so much. I have finally figured it out.
